# Generated by Django 4.1 on 2022-08-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
